- name: Enable services
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Check OS type and version
      set_fact:
        os_type: "{{ ansible_os_family }}"
        os_version: "{{ ansible_distribution_version }}"
        os_distribution: "{{ ansible_distribution }}"


    - name: Debug OS type and version
      debug:
        msg: "OS Distribution: {{ os_distribution }}, OS Version: {{ os_version }}, OS Type: {{ os_type }}"
